services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: scarelli
      POSTGRES_PASSWORD: neymardemoicano2011
      POSTGRES_DB: db_gobank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
